// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjCXpJm9NW3pd0YjHGrXnhxmPQDvIFuXI',
    appId: '1:618267460887:web:dd39997716bdc662822352',
    messagingSenderId: '618267460887',
    projectId: 'alhaytham-d6298',
    authDomain: 'alhaytham-d6298.firebaseapp.com',
    storageBucket: 'alhaytham-d6298.firebasestorage.app',
    measurementId: 'G-605DZ9HQ68',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDNWy1cvxYr-4MBSH-s88JrhkNouQRLVc',
    appId: '1:618267460887:android:3d4e4090e0150960822352',
    messagingSenderId: '618267460887',
    projectId: 'alhaytham-d6298',
    storageBucket: 'alhaytham-d6298.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1oEse6_yYjE5ecJUbOE_U9YJwYDbvLmg',
    appId: '1:618267460887:ios:e6b0b545086db1e0822352',
    messagingSenderId: '618267460887',
    projectId: 'alhaytham-d6298',
    storageBucket: 'alhaytham-d6298.firebasestorage.app',
    iosBundleId: 'gh.almashi.alhaytham',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1oEse6_yYjE5ecJUbOE_U9YJwYDbvLmg',
    appId: '1:618267460887:ios:e8dbb33677d2b21a822352',
    messagingSenderId: '618267460887',
    projectId: 'alhaytham-d6298',
    storageBucket: 'alhaytham-d6298.firebasestorage.app',
    iosBundleId: 'com.example.baheth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjCXpJm9NW3pd0YjHGrXnhxmPQDvIFuXI',
    appId: '1:618267460887:web:c095f4a0cff791b6822352',
    messagingSenderId: '618267460887',
    projectId: 'alhaytham-d6298',
    authDomain: 'alhaytham-d6298.firebaseapp.com',
    storageBucket: 'alhaytham-d6298.firebasestorage.app',
    measurementId: 'G-ZJK69CCCSK',
  );
}
